### ISSUE TITLE
`Deprecated soon` too ugly...

### ISSUE THREAD

**Issue by recolic** [recolic/awesome-hust#52] opened 2021-09-07 08:21 UTC
This section is too ugly, but I have no idea about how to improve it... So let's discuss... 

![image](https://user-images.githubusercontent.com/19610256/132310384-fb705fec-2d71-47c8-b718-2a3c3d8ef028.png)

I think we can change it to `[Deprecated soon] 大学物理网考答案 xxxx`, but it's also not good enough... 

Any idea about this?

**Comment by GrayXu** [comment] 2021-09-07 08:29
`details` tag?  

e.g.:  
```
<details>
  <summary>[Deprecated soon] 大学物理网考答案 xxxx</summary>
  balabala...
</details>
```

<details>
  <summary>[Deprecated soon] 大学物理网考答案 xxxx</summary>
  balabala...
</details>

**Comment by MacsedProtoss** [comment] 2021-09-29 07:23
since those items were marked as 'deprecated soon' for a long time, maybe we could consider move it to another file OR check if it had been confirmed the depreciation and remove it.

**Comment by recolic** [comment] 2021-09-29 07:48
Just double-confirm it. If it's useless, remove them. If it's
      still useful, remove `deprecated soon`... 
    
    I believe the "deprecated soon" tag doesn't make sense at all...
    
    -- 
Recolic Keghart
***@***.***
Mail from China goes: ***@***.***
    On 9/29/21 15:23, Macsed Protoss wrote:
    
    
      
      since those items were marked as 'deprecated soon' for a long
        time, maybe we could consider move it to another file OR check
        if it had been confirmed the depreciation and remove it.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/recolic/awesome-hust/issues/52#issuecomment-929910552",
"url": "https://github.com/recolic/awesome-hust/issues/52#issuecomment-929910552",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Closed** 2022-11-10 22:53 UTC
